---
bibliography: ms.bib
csl: meps.csl
site: "bookdown::bookdown_site"
output:
  bookdown::word_document2:
    toc: FALSE
    fig_caption: yes
indent: TRUE
monofont: "Times New Roman"
fontsize: 12pt
header-includes:
  - \usepackage{setspace}
  - \doublespacing
---

```{r setup, include=FALSE}
library(knitr)
library(bookdown)

	# Configure knitr, see http://yihui.name/knitr/options
	opts_knit$set(
	  progress=TRUE,
	  verbose=TRUE)
	opts_chunk$set(
	#  include=FALSE,
	  cache=TRUE,
	  echo=FALSE,
	  message=FALSE
	 )
knitr::opts_chunk$set(echo = TRUE)
```

# Characterizing the Secret Diets of Siphonophores (Cnidaria: Hydrozoa) using DNA Metabarcoding

Alejandro Damian-Serrano^1^^,‡^, Elizabeth D. Hetherington^2^, C. Anela Choy^2^, Steven H.D. Haddock^3^, Alexandra Lapides^3^, Casey W. Dunn^1^   (order open to suggestions)

^1^ Yale University, Department of Ecology and Evolutionary Biology, 165 Prospect St., New Haven, CT 06520, USA

^2^ Scripps Institution of Oceanography, University of California San Diego, Integrative Oceanography Division, La Jolla, CA, 92037, USA

^3^ Monterey Bay Aquarium Research Institute, 7700 Sandholdt Rd., Moss Landing, CA 95039, USA

\‡ Corresponding author: Alejandro Damian-Serrano, email: alejandro.damianserrano@yale.edu

\newpage

## Abstract {-}

Siphonophores are abundant and diverse predators in the open-ocean ecosystems. Due to limited access to the deep midwater environment, little is known about the diets of most deep-dwelling species. Visual gut content inspection is a powerful approach, but can rarely identify soft-bodied prey that do not leave recognizable parts behind. Observations of feeding from submersibles through video recordings are useful for deeper species, but are unable to identify small prey items (such as copepods, ostracods, and larval fish). Recently, the application of DNA metabarcoding in other marine predators has revealed the importance of prey taxa that were overlooked by these visual methods. Moreover, metabarcoding can detect prey that was ingested hours before specimen collection and thus is better suited for the study of deep-sea species with long intervals between prey captures. In this study, we perform DNA metabarcoding analyses on the gut contents of several siphonophore species across depths and describe their diets. We collected siphonophore specimens using blue water dives and ROV dives in open-ocean waters. We extracted DNA from the feeding bodies, then amplified and sequenced six regions along the 18S gene. Taxonomic identifications were assigned to prey OTUs using SILVA databases combined with local zooplankton sequences. We find that most of the species analyzed here are specialized and strongly selective predators. Many of the interactions detected by our metabarcoding analyses are congruent with predictions based on tentilla morphology. In addition, our analyses were able to detect small prey and gelatinous prey taxa underrepresented by visual methods. Our results reveal hidden links between siphonophores and the lowest trophic levels in the midwater food-web. This study expands our understanding of the role of siphonophores in the open ocean, and the importance of their species diversity for nutrient flow and ecosystem functioning.

## Keywords {-}

Siphonophore, trophic ecology, prey selectivity, DNA metabarcoding

## Introduction {-}

The open-ocean midwater is the largest volume of the biosphere habitable by animals [@harbison1992gelatinous]. This environment hosts diverse communities and complex food webs [@robison2004deep]. Midwater food webs sustain manifold fisheries, charismatic megafauna, and sustain the biological carbon pump. Gelatinous animals play fundamental roles in these food webs [@choy2017deep], acting as herbivores, predators, and prey in the ‘jelly web’ [@robison2004deep;@chi2020tackling]. Among the most important gelatinous predators are siphonophores, mid-trophic predators that feed on a broad variety of prey taxa such as medusae, salps, crustaceans, molluscs, and fishes [@purcell1981dietary; @hetherington2021moving]. Siphonophores are sit-and-wait, non-visual, ambush predators that rely on prey coming into contact with the tentacles and tentilla [@mackie1988siphonophore]. They are abundant and locally diverse colonial cnidarians in open-ocean communities, present in every ocean of the world, with species ranging from the surface (like the Portuguese man-o-war) to the abyssopelagic region (>4000m deep) [@mapstone2014global]. In addition, siphonophore aggregations can have significant predatory impacts on larval fish stocks [@purcell1981feeding]. 

Progress in elucidating siphonophore diets has been slow due to the intrinsic challenges of working with these animals. Oceanic taxa require expensive research vessels to reach their habitat. In addition, siphonophores are extremely fragile creatures, requiring the use of blue water SCUBA divers and Remotely Operated Vehicles (ROVs) to collect them alive and intact [@haddock2004golden]. Both these techniques can be used to collect live specimens for gut content inspection, and video recordings from ROVs also allow scientists to observe feeding events. Traditional collection methods such as plankton nets not only break up the colonies, but also lead to artifactual ingestions in the cod-end that confound their natural diets. 

The diets of some epipelagic and siphonophore species are well known through gut content analyses of SCUBA-collected colonies [@biggs1977field;@purcell1981dietary; reviewed in @hetherington2021moving]. Recent studies based on ROV observations have shed some light on the diets of deep midwater siphonophores [@choy2017deep; @hetherington2021moving;@lapides2021prey]. However, both of these approaches have been limited by their biases. Visual gut content inspection only recognizes hard-bodied prey that digest slowly, leaving behind diagnostic body parts (i.e. exoskeleton, shell, eyes…). Therefore, these methods are biased against soft-bodied, rapidly-digested taxa, such as gelatinous zooplankton. ROVs are able to observe feeding on gelatinous prey before it becomes digested. However, ROV observations are skewed towards large prey items that can be easily identified from the camera screen (such as jellyfish, shrimps, or fish), thus overlooking important prey items such as copepods and larvae [@hetherington2021moving]. In addition, prey are scarce in the open ocean, especially in the deeper regions [@robison2004deep], thus it is relatively rare to find specimens capturing prey or carrying visually-identifiable prey in the guts. 

With the advent of DNA metabarcoding, the diets of many marine predators have been established from gut content DNA [@leray2013new;@harms2016use;@van2018preliminary ;@fernandez2018predatory]. These high-throughput amplicon sequencing technologies have extremely high detection sensitivity and bypass the biases posed by visual methods. In the past few years, the application of DNA metabarcoding to marine predator gut contents has demonstrated the capacity of these methods to detect gelatinous prey [@connell2014dna;@mcinnes2017high;@clarke2018dna;@jensen2018tracing;@marques2019molecular]. However, this technology has not yet been applied to study the diets of gelatinous animals.

In Hetherington et al. @hetherington2021moving, we reviewed and summarized the literature on siphonophore diets, and observed significant differences between the diets of epipelagic and deep-swelling siphonophore species. Gelatinous prey appeared to be more prevalent in deep-sea observations while small crustaceans appeared to be the predominant prey in shallow gut content samples. Since epipelagic species’ diets were exclusively assessed through microscopic gut content inspection and deep-sea species’ diets through ROV observations, it is not possible to determine whether these differences are due to ecological or methodological reasons. In order to disentangle these confounding factors, it is critical to assess both shallow and deep species’ diets under the same methodological framework. In this case, DNA metabarcoding is an ideal choice, since it is able to detect both small and gelatinous prey, thus being able to bridge across the methodological shortcomings of visual methods.

In Damian-Serrano et al. @damianserrano2022evolutionary, we generated feeding guild predictions for 45 understudied siphonophore species using the discriminant analysis of principal components (DAPC) functions generated from the analyses in [@damian2021evolution]. These analyses captured the complex multivariate relationships between tentilla and nematocyst morphology and feeding guild (based on published dietary assessments for 22 species). These predictions remain to be tested with new data on siphonophore diets.

Here we use DNA metabarcoding to identify the gut contents of several siphonophore species to obtain insights into their diets. The primary aims of this study are: (1) Expand the existing knowledge on the diets of open-ocean siphonophores using DNA metabarcoding, (2) compare the prey detected by visual and molecular methods to evaluate their technical biases, (3) compare the prey found in the gut contents to the local planktonic community composition to identify instances of selectivity and specialization, and (4) evaluate the morphology-based predictions of feeding guild generated in Damian-Serrano et al. @damianserrano2022evolutionary.

## Methods {-}

*Siphonophore collection* — In order to sample a representative set of taxa across the siphonophore phylogeny, we targeted a set of 41 species including cystonects, apolemiids, pyrostephids, euphysonects, and calycophorans from shallow and deep waters. Most species were sampled from the Offshore California Current Ecosystem (OCCE) with the exception of the Portuguese man-o-war *Physalia physalis*, which was collected off Bermuda in the Sargasso Sea; *Sulculeolaria chuni* and some *Nanomia* sp. (labeled as “Atlantic”) which were collected off Rhode Island in the Block Island sound. While all the *Nanomia* populations sampled in this study has been referred to as *N. bijuga*, we suspect that there may be undescribed cryptic *Nanomia* species among the specimens sampled. Therefore, we decided to have them labeled at the genus level. The pleustonic (surface floating) *Physalia physalis* samples were collected using a bucket from a small boat. The epipelagic species found between the surface and 20m deep were collected using blue water diving techniques following the guidelines in Haddock & Heine @haddock2005scientific. The deep-sea species living between 200m and 4000m were collected using ROVs. All animals were collected live and brought back to the ship (or field station in Bermuda for *P. physalis*) for dissection (Fig. \@ref(methods_fig)). Live colonies were photographed (sometimes recorded on video), and zooids of diagnostic value (nectophores, bracts, tentacles) were dissected, fixed in 4% formalin, and stored as vouchers at the Yale Peabody Museum of Natural History.

*Gut content metabarcoding* — Shortly after collection of the live specimens, we dissected and pooled several gastrozooids, prioritizing those with visible gut contents, in addition to any visible egested food pellets at the bottom of the sampling container. Samples were frozen at -80°C until DNA extraction. Further details on the DNA extraction, quality control, PCR, amplicon purification, and amplicon pooling are fully described in the online protocol [@damianserrano2020dna]. All molecular bench work was carried out at the Yale DNA Analysis Facility. We used a set of six primer pairs that amplify six regions within the 18S gene (and part of the ITS1) named after their expected amplicon length (‘134’, ’152’, ’166’, ’179’, ’261’, and ‘272’). The primers were designed using Geneious v.x.x.x. [@kearse2012geneious], seeking short (>300bp) amplicon products with a high chance of remaining uncleaved after digestion in the gastrozooid, flanked by priming sites conserved (to a maximum mismatch of 3bp) across metazoans. The search for conserved priming sites was conducted on an alignment of 18S genes from 975 species across all metazoan phyla downloaded from GenBank. The primer search was optimized to only retrieve primer pairs with compatible annealing temperatures and without problematic dimerization and hairpin temperatures. Primer sequences and properties can be found in Table T1 in Damian-Serrano @damianserrano2020dna. Amplicon pools were sequenced using Illumina MiSeq 250bp paired-end technology (except samples in run 0 which was sequenced using MiSeq 150bp) at the Yale Center for Genomic Analysis.

![\label{methods_fig} Figure 1. Gut content metabarcoding workflow used in this study. Siphonophore colony illustrated by Freya Goetz. Silhouettes in the plankton net downloaded from phylopic.org. Solid arrows indicate physical material transfer and processing, dashed lines indicate information transfers and processing. Yellow islands indicate elements processed in the laboratory bench, green islands represent bioinformatic datasets processed in the high-performance computing cluster, and red islands represent curated data products.](Figures/methods_stream.png)


*Prey reference database* — In order to enhance the accuracy of the taxonomic assignments of reads, we also built a complementary custom reference 18S gene barcoding database. To do this, we collected 60 specimens of 30 species of zooplankton and micronekton from the OCCE using a mini-tucker trawl net. We targeted species from underrepresented oceanic clades in SILVA databases, including fishes, crustaceans, jellyfishes, urochordates, chaetognaths, polychaetes, and mollusks. Specimens were photographed live, tissue was sampled and frozen, and the rest of the animal was fixed in formalin as a voucher to be identified and preserved at the Yale Peabody Museum of Natural History. DNA extraction, quality control, PCR, and amplicon cleanup was carried out in a similar fashion as the metabarcoding protocol in Damian-Serrano @damianserrano2020dna, with the exception that only one PCR program was used (Damian-Serrano @damianserrano2020dna, Table T5A), and only one pair of primers was used (166F and 134R), spanning the full extent of the sequence containing all barcode regions used in the gut content metabarcoding (~1800bp). Purified amplicons were sent in plates with the forward and reverse primer separately for Sanger sequencing from both ends at the Yale DNA Analysis Facility. These sequences were then assembled and trimmed at a 95% quality cutoff in Geneious, and concatenated with the latest SILVA database (SILVA_138_SSURef_NR99 pruned to remove bacterial sequences) downloaded on February 23rd (2021) to generate our custom-built database.

*Bioinformatic pipeline* — Amplicon libraries were demultiplexed by primer sequence using custom bash code. Primer sequences were removed using *cutadapt* [@martin2011cutadapt]. The forward and reverse reads were matched and repaired using *bbtools* [@bushnell2017bbmerge], then denoised and de-replicated using the DADA2 [@callahan2016dada2] plugin in QIIME2 [@bolyen2019reproducible] with a truncation quality threshold of 28. We *de novo* clustered the unique features into OTUs using the VSEARCH [@rognes2016vsearch] plugin in QIIME2 with a similarity threshold of 95%. Using QIIME2, we computed sample composition and diversity metrics and aligned the feature sequences with MAFFT [@katoh2009multiple] to build a phylogenetic tree with Fasttree [@price2009fasttree]. To reduce computational load, only the top 100 most abundant features among the clustered OTUs were selected for taxonomic assignment. Taxonomic identifications were assigned using the assignment software METAXA2 [@bengtsson2015metaxa2] with a 70% reliability cutoff, comparing the sequences against the standard GenBank reference library, the SILVA123.1 reference library [@quast2012silva], and our custom-built library (based on SILVA138). All bioinformatics analyses were carried out in the Yale High Performance Computing Cluster. The taxonomic assignments and read count data were merged, then parsed to match the sample of origin and the DNA sequence they derived from. Sequence post-processing scripts can be found in the GitHub repository (https://github.com/dunnlab/siphweb_metabarcoding).

*Assignment interpretation* — Taxonomic assignments were then manually inspected and annotated with the interpreted consensus taxon and interpreted source (predator, prey, secondary predation, parasite, environmental eukaryote, unrecognizable sequence, contamination, or cross contamination). A combination of annotation database consensus, barcode region consensus, number of reads, manual BLAST checks, and natural history informed priors were used to assign these interpretations. Amplification experiments on negative controls indicated that the human, mite, and insect contaminants originated from specimen manipulation in the field and not from the lab bench. Cross-contamination at the lab bench was suspected for some samples in runs 0 and 5 due to simultaneous DNA extractions of reference prey samples. Reads which were suspected of cross-contamination (assigned to taxa present in the potential sources of contamination, present across multiple samples in the same run with very low read abundances) were conservatively labelled as such. Crustacean, gastropod, and larvacean sequences in *Physalia* samples were interpreted as secondary predation (prey of their fish prey) given our knowledge on the prey-capture limitations of these animals and the feeding habits of their fish prey. When all barcode regions except ‘152’ indicate mysid prey but ‘152’ identifies a similar number of reads as stomatopod prey, we interpreted those reads as mysid prey. Assignments of shark identities by barcode region ‘152’ in one of the *Physalia* samples (extraction 169) were identified as ray-finned fish prey using BLAST searches and interpreted as such, in agreement with the other barcode regions. Assignment of decapod crustacean identities by barcode region ‘152’ (in extractions 111, 218, and 225) were interpreted as euphausiid prey in agreement with the assignments on the rest of the barcode regions. The taxonomic composition of the samples was analyzed and visualized in the R programming environment. Scripts and data available in our GitHub repository (https://github.com/dunnlab/siphweb_metabarcoding).

*Prey field characterization* — In order to compare the observed diet to the environmental abundances of potential prey taxa, we collected zooplankton and micronekton samples the same day and location (cruise station coordinates) as the gut content samples they are paired with. The plankton samples paired with epipelagic siphonophore specimens were collected using a weighted hand-held plankton net (ring diameter of 1m for the Bermuda samples, 0.5m for the OCCE and Block Island sound samples, mesh size of 250µm) towed for ~10min at a few meters under the surface at a speed of ~1kt. Paired with the ROV-collected mesopelagic siphonophore specimens, we collected macroplankton and micronekton samples using a mini-tucker trawl net (frame area: 2m^2^, mesh size: 500µm) towed for ~2h between 900m and the surface at night. Environmental community samples were visually examined live to collect specimens to sequence for the 18S reference library and other purposes, which were annotated as removed. Samples were concentrated using metal sieves and fixed in 4% formalin. Back in the Yale Peabody Museum of Natural History, these samples were visually identified and quantified from a splitter aliquot. In order to estimate how selective siphonophore species are for different prey types in the environment, we calculated Strauss @strauss1979reliability Linear Index (LI).

*Comparisons to published sources* — In this study we aim to compare and expand previous predation results from submersible observations and visual gut content inspections with the new results of DNA metabarcoding of gut contents. Therefore, we used the dietary data compiled in Damian-Serrano et al. @damian2021evolution from eleven published sources divided into those that used gut content inspections and those that used submersible observations. Salps, ctenophores, and medusae were merged into a gelatinous prey concept for comparative purposes. Published records for *Apolemia uvaria* were considered equivalent to *Apolemia* sp. for genus level comparisons. Records of all *Forskalia* species were considered equivalent to *Forskalia* sp. In order to test the morphology-based dietary predictions generated in Damian-Serrano et al. @damianserrano2022evolutionary, we used the Bayesian posterior probabilities for each feeding guild for each species. Small-crustacean guild predictions were mapped to copepod, ostracod, and cladoceran prey concepts. Large-crustacean guild predictions were mapped to decapod, euphausiid, mysid, lophogastrid, stomatopod, and amphipod prey concepts. Generalist guild predictions were mapped to all prey concepts except gelatinous prey (following the intended distinction with gelatinous specialists used in Damian-Serrano et al. @damian2021evolution).

## Results {-}

We extracted, amplified, and sequenced the gut contents of 159 specimens from 41 siphonophore species. We obtained a total of 4148 unique sequences, including 1502 sequences from region “134”, 614 from region “152”, 758 from region “166”, 497 from region “179”, and 341 from region “261”, and 442 from region “272”. A total of 337 unique sequences were interpreted as prey items, 36 as secondary predation, 292 as contamination from extrinsic sources, 2857 as natural environmental DNA sources, 791 as siphonophore sequences, 85 as parasites (myxozoans, trematodes, and other helminths), and 14 unrecognizable sequences. We identified prey items in 47 specimens from 24 species. We identified 55 unique prey items, 42 of which were crustaceans (25 of which were copepods), three of them were fishes, four of them were thaliaceans, five corresponded to other gelatinous predators (ctenophores and a medusa), and one matching to a bivalve mollusc. Most (112 out of 159) siphonophore specimens collected did not yield any putative prey concepts. Among the 47 specimens with prey, 40 of them had DNA from a single prey item, while only six had two prey items, and one *Apolemia* sp. specimen had three prey items (SM-Figure 1). This is consistent with the feeding habits of sit-and-wait ambush predators in oligotrophic environments, with scarce feeding events separated by periods of starvation.

![\label{spp_gcsel} Figure 2. Species-wise grid with the frequency of the major prey types identified from the metabarcoding data (left) and the average prey-type selectivity estimated in comparison with the local planktonic community composition (right). Gut content cells in white indicate absence, and in cells in grey indicate presence in one specimen, or more than one specimen if labeled with a number. Selectivity heatmap mapped to Strauss’ L.I. values. Phylogenetic cladogram based on the tree published in Damian-Serrano et al. (2021).](Figures/GC-SEL_spp.png)

When comparing the identified prey to the co-localized prey field, we only find strong negative (<-0.5) selectivity for copepods in *P. physalis* specimens and in one specimen of *Vogtia serrata*. We do find strong positive selectivity (>0.5) in 19 specimens from 12 species (out of the 15 species assessed). These cases include: selectivity for fish in *P. physalis*; selectivity for copepods in *Lensia conoidea*, *Chuniphyes multidentata*, *Desmophyes annectens*, *S. chuni*, and Atlantic *Nanomia* sp.; selectivity for ostracods in *Vogtia serrata*; selectivity for decapods in *Lychnagalma utricularia*, for lophogastrids in *Halistemma rubrum*, and for mysids in *Apolemia* sp.; and selectivity for salps in *Apolemia rubriversa* and *Diphyes dispar* (Fig. \@ref(spp_gcsel)). Comparing our metabarcoding findings with the morphology-based predictions from Damian-Serrano et al. @damianserrano2022evolutionary, we confirmed 15 predicted interactions between siphonophores and prey. On the other hand, among the species studied there were 70 predicted interactions that were not confirmed by the metabarcoding results (Fig. \@ref(source_comparison)). Out of the 10 taxa with both morphology-based predictions and metabarcoding results, six had all prey congruent with the predictions, three had all prey incongruent with the predictions, and *Forskalia* sp. presented both cases.

![\label{source_comparison} Figure 3. Feeding interactions between siphonophore species and their prey identified by our metabarcoding results (red), published submersible observations (blue), published visual gut content analyses (green), and predicted by the morphology-based DAPC model in Damian-Serrano et al. (2021).](Figures/Source_comparison_compact.png)


We reported the first insights into the diets of nine siphonophore species, and revealed 29 novel predator-prey interactions (Fig. \@ref(source_comparison)). When comparing our metabarcoding findings with the published visual observations from gut content inspections and submersible dives, we found five interaction congruent with ROV observations, and eight interactions (six of them involving copepods) congruent with visual gut content inspections of SCUBA-collected colonies (Fig. \@ref(source_comparison)). Our novel findings suggest that visual inspections of gut contents may have missed gelatinous prey in *P. physalis*, and potentially missed larvacean prey in *Apolemia* and *Muggiaea atlantica*. In mesopelagic species, we suspect that submersible observations may have missed copepod prey in *D. annectens*, *Forskalia* sp., and *Apolemia* sp.; ostracod prey in *Bargmannia elongata*; and larvacean prey in *Apolemia* sp.
	
The Portuguese man-o-war (*P. physalis*) is the only pleustonic (surface floating) member of the siphonophores, and the most commonly encountered by beachgoers. In our gut content samples from Bermuda, we found three specimens with ray-finned fish sequences, some of which had visually recognizable fish in the gastrozooids when collected. Fish prey is congruent with published visual inspections of their gut contents [@purcell1984predation;@bardi2007taxonomic]. In all three specimens with fish prey we also found benthic and hard-bodied taxa (mysid, alpheid shrimp, spider crab, copepod, benthic gastropod, and a sipunculid worm), as well as larvacean sequences. Man-o-wars are well-known to feed exclusively on relatively large and motile soft-bodied prey such as fish, chaetognaths, or pelagic gastropods [@purcell1984predation]. Their nematocysts are not able to subdue crustacean prey, and their feeding reflex would not trigger with a prey as small as a larvacean. Therefore, we interpreted the presence of these taxa in the gut contents as secondary predation (prey of the fish prey). In addition, we also detected a ctenophore in the gut contents of one specimen. This could be also a case of secondary predation, but we suspect a ctenophore could be large enough to be prey of the man-o-war. If that is the case, this would be the first record of *P. physalis* consuming gelatinous zooplankton, which would place the man-o-war as a central species in the epipelagic ‘jelly-web’ [@chi2020tackling]. Comparisons with their surrounding prey field show these specimens were strongly selective for fish and strongly exclusive of copepods (Fig. \@ref(spp_gcsel)).

*Apolemia* physonects are among the longest siphonophores, with colonies reaching as long as 30m of length [@mackie1988siphonophore]. Their tentacles are different from other siphonophores since they have no tentilla, and carry birhopaloid heteroneme nematocysts directly on the tentacles [@damianserrano2022evolutionary]. *Apolemia* species are known to consume diverse prey including crustaceans, molluscs, polychaetes, chaetognaths, fish, and gelatinous zooplankton [@purcell1981dietary;@choy2017deep]. While this may suggest these species are generalists, Damian-Serrano et al. @damian2021evolution hypothesized that they may be gelatinous zooplankton specialists, since they consume a larger proportion of this prey type than other siphonophores. In addition, the nematocysts of *Apolemia* have similar traits to those in other gelativore cnidarians [@purcell19881988], and their apparent generality could be explained by the sheer number of fine tentacles deployed for prey capture per colony, which would inevitably entangle almost anything that swims by. All species of *Apolemia* analyzed here had consumed copepods, the *A. rubriversa* had also consumed a salp, and the undescribed *Apolemia* species also had ctenophore, larvacean, mysid, and euphausiid prey sequences. The high selectivity of *A. rubriversa* for salp prey is congruent with its characterization as a gelatinous specialist in Damian-Serrano et al. (2021). The morphology-based predictions derived from Damian-Serrano et al. @damianserrano2022evolutionary indicate that *A. lanosa* should be a gelatinous prey specialist. This is incongruent with our finding of just copepod prey, but it is possible that the doliolid and hydromedusa reads we conservatively labelled as potential cross-contamination could correspond to real prey. In light of these interspecific differences, it is possible that these coexisting species of midwater *Apolemia* are partitioning their trophic niche by varying the proportion of crustacean versus gelatinous prey they consume.  

The three species of *Bargmannia* considered here are frequently-observed siphonophore species in the midwaters off Monterey Bay. These physonects have relatively simple tentilla with large stenotele nematocysts and an undifferentiated terminal filament [@damian2021evolution]. ROVs have recorded *B. elongata* consuming crustaceans and cephalopods, and during specimen collection we observed a mysid prey in a specimen *B. amoena*. Nothing was previously known, however, about the diet of *B. lata*. DNA metabarcoding confirmed the identity of the mysid in *B. amoena* as *Boreomysis californica*, and found a copepod in another specimen. One *B. elongata* specimen had euphausiid and ostracod prey, in agreement with the DAPC prediction for *B. elongata* to feed mainly on large crustaceans, but also marginally on small crustaceans. The two *B. lata* specimens were consuming a ctenophore and a copepod respectively. These results are not congruent with the morphology-based prediction for *B. lata* to be a large-crustacean specialist (Fig. \@ref(source_comparison)), which suggests that the lack of taxon sampling among the pyrostephids could have biased the model. The diets of these three closely related, coexisting species appear to be non-overlapping, which could be a consequence of competitive trophic niche segregation.

Other deep-sea physonects also present interesting results. Undescribed physonect sp. L was predicted to be a fish specialist with a secondary affinity for large crustacean prey. However, we found this specimen consuming a ctenophore, revealing yet another hidden link to the ‘jelly-web’. *Resomia dunni* was predicted to be a generalist (consumer of all types of prey except gelatinous taxa), which is not incongruent with the copepod prey we found in its gut contents. *Forskalia* species have been observed to consume various crustaceans, molluscs, worms and fish [@purcell1981dietary]. Morphology predicts *Forskalia* species to be large crustacean specialists. We found three midwater *Forskalia* specimens with copepod prey in the guts, one of them also had consumed a sergestid shrimp. These results are fully congruent with those derived from visual methods, and partly congruent with the morphological predictions. *L. utricularia* is unique among the physonects for bearing a medusa-shaped floating vesicle at the end of their large, coiled tentilla. They have been observed through ROVs consuming sergestid shrimp. We found two specimens both with sergestid shrimp prey (for which they are strongly selective), yet one of them was also digesting a euphausiid. This is consistent with their large-crustacean specialization. *H. rubrum* tentilla closely resemble those of *Forskalia*, and thus they are also predicted to be large-crustacean specialists. This prediction is congruent with our identification of a lophogastrid in the gut contents for which it was strongly selective.

*Nanomia* species are among the most common siphonophores in both Atlantic and Pacific waters, both in epipelagic and midwater environments. We have observed that epipelagic *Nanomia* tend to have smaller tentilla than their mesopelagic counterparts, which may account for their specialization on smaller crustaceans (such as copepods) instead of larger crustaceans (such as krill). Midwater ROV observations of deep-dwelling *Nanomia* have predominantly reported interactions with krill prey, as well as with the occasional chaetognath or sergestid shrimp. We identified one specimen of mesopelagic *Nanomia* with krill and stomatopod DNA in its gut contents, in agreement with its large-crustacean specialist characterization. Epipelagic *Nanomia* might not be as specialized on large crustacean prey, since the literature reports a combination of copepod, decapod, mysid, and chaetognath prey. In the North Pacific Ocean, our metabarcoding identified copepod prey in an epipelagic *Nanomia* off California, a hyperiid amphipod prey in an epipelagic *Nanomia* off Hawaii. This amphipod could have been a commensal or parasite on the *Nanomia* instead of prey, though this is unlikely since only the gastrozooids were dissected while amphipods tend to colonize the nectophores or bracts. In the North Atlantic Ocean, we sampled 14 specimens of epipelagic *Nanomia*, seven of which contained copepod prey. Upon visual inspection of the sampled gastrozooids we could identify *Temora*, *Centropages*, and *Acartia* copepods, the most abundant genera in the plankton sample, whose identity was also confirmed by the metabarcoding results. The corresponding environmental plankton samples showed that these waters were dominated by cladocerans, and thus these *Nanomia* were positively selecting for copepod prey and selecting against cladoceran prey (not detected in the guts). The exclusion of the overabundant cladocerans from the diet of these *Nanomia* suggests that their specialization could be copepod-specific.

Calycophorans are characterized by their lack of a pneumatophore (gas-filled apical vesicle) and their structurally-homogeneous tentilla @damianserrano2022evolutionary. However, these tentilla present a great variation in nematocyst number and size, which may translate into dietary differences. *Vogtia* is the closest relative to *Hippopodius*, the only siphonophore known to be an ostracod specialist [@purcell1981dietary]. Like many other hard-to-access mesopelagic taxa, the diet of *Vogtia* has remained unknown, though tentilla morphology predicts them to be generalists [@damianserrano2022evolutionary]. Pugh @pugh1986trophic found spatial correlations between ostracods and *Vogtia* species, and even mentions a *Vogtia* sp. specimen which had the exoskeleton of an ostracod in its gut contents. Our DNA metabarcoding on *V. serrata* has revealed one specimen feeding on an ostracod, and a specimen feeding on a sergestid shrimp and a bivalve. These results are consistent with the generalist morphological prediction, and congruent with the single visual finding of an ostracod in a congener from Pugh @pugh1986trophic. The presence of an ostracod and a bivalve (likely a pediveliger larva), which has a very similar shape to an ostracod (with two hard valves), indicates phylogenetic conservatism of prey traits within Hippopodidae. This is also supported by the fact that the ostracod capture appears to be highly selective given the corresponding community composition.

We provided the first insights into the diets of two highly abundant deep-sea calycophorans, *L. conoidea* and *Chuniphyes multidentata*, which morphology predicted as small-crustacean specialists. Both sequenced specimens had copepod DNA, confirming these predictions. Gelatinous prey has been reported for calycophorans (such as *P. dubia* or *D. annectens*) from ROV observations. We report the first instances of gelatinous prey in *Diphyes dispar* (salp prey), *M. atlantica* (larvacean), and *Sphaeronectes christiansonae* (nausithoid medusa). The latter interaction constitutes the first record of *S. christiansonae* feeding. While nausithoid medusae can be very small, the minute size of this siphonophore renders this interaction dubious. The far more common epipelagic *Sphaeronectes* species, *S. koellikeri*, appears to be a copepod specialist according to visual gut content analysis [@purcell1981dietary]. We sequenced the gut contents of two specimens of this species, one of them indeed was consuming a copepod, yet the other was consuming a crab larva, which constitutes a novel prey type for this species, yet still within the expected range of a small-crustacean specialist. Another confirmed expectation occurred with *S. chuni,* a visually-assessed copepod specialist in Purcell @purcell1981dietary, for which we detected a copepod prey in an Atlantic specimen.

## Discussion {-}

This study constitutes the first use of DNA metabarcoding for siphonophore gut contents, as well as the first application of this technology to investigate the diets of marine gelatinous predators. Our results expand the existing knowledge on siphonophore diets, detecting prey types previously missed by visual methods, and providing the first insights into the diets of several understudied siphonophore species. By comparing the taxonomic composition of the gut contents to that of the environmental planktonic community, we confirm that most of the examined siphonophore species are strongly selective specialists (Fig. \@ref(spp_gcsel)). Moreover, we find that many of the tentilla morphology-based dietary predictions for these species were confirmed by the metabarcoding results (Fig. \@ref(source_comparison)). We show that whole gastrozooids can be utilized for DNA metabarcoding of diets without need for further dissection nor the use of predator blocking primers.

We identified representatives from diverse animals (SM-Figures 6-9), which demonstrates the phylogenetic range of taxa that can be amplified with our primer pairs. Overall, crustaceans (especially copepods) were identified as the most frequent prey type among siphonophore diets. Copepods are typically the most abundant prey type in planktonic communities, thus being able to feed on them is likely an advantageous strategy for any planktivorous predator. Fish prey were detected only in the Portuguese man-o-war samples, in agreement with published observations of man-o-war feeding. For most siphonophore species assessed herein, their prey belonged to the rarer components of the planktonic community, demonstrating high prey selectivity. However, the selectivity index values presented in this study should be interpreted with care, since the prey field data is quantitative (abundance-based) but the gut content values are only binary at the specimen level, and frequency-based at the species level.

We have detected prey types previously missed by visual methods (microscopic gut content observations and submersible observations) such as larvaceans, ctenophores, bivalves, and ostracods. These results are consistent with the hypothesis that small prey is underestimated in submersible observations and rapidly-digested prey is underestimated by gut content inspections. DNA metabarcoding was able to detect prey both small and large, gelatinous and hard-bodied, for both deep and shallow-dwelling species. In Damian-Serrano et al. @damianserrano2022evolutionary we predicted the diets of understudied siphonophore species based on the morphology of their tentilla and nematocysts. We were able to test these predictions for ten species, and found that most of the prey items found were congruent with these predictions, indicating that tentilla morphology is a strong predictor of siphonophore diets. Our findings are congruent with the idea that most epipelagic and mesopelagic siphonophore species are strongly selective and specialized predators. Different species were found consuming prey across low (salps, larvaceans, copepods, ostracods) and high (fish, ctenophores, medusae) trophic levels. In addition, finding of larvaceans and salps in the diets of four species should shift our perspective on the role of siphonophores in open ocean food-webs, as they may be able to directly feed filter-feeding prey at lower trophic levels, potentially placing some species as close as one trophic level away from phytoplankton productivity and the microbial loop.

While DNA-based tools can detect prey unrecognized by visual methods, they are not free of shortcomings. Since all life stages of an animal have the same genetic signature, metabarcoding tools are unable to distinguish between larval, juvenile, or adult prey. These ontogenetic stages can have vastly different ecological implications and pose radically different challenges during prey capture. In addition, the application of metabarcoding to predator diets is usually not quantitative, since too many sources of variation may lead to differences in read abundance. For example, different animal clades have different sizes, cell densities (due to variable acellular mesoglea content), digestion rates, number of copies of the target gene, or primer affinities during the PCR [@deagle2007quantitative ;@troedsson2009quantification;@valentini2009new]. Due to the difficulties inherent to locating and sampling the species examined in this study, frequency-based quantitative comparisons were not possible for most species either.

Siphonophores differ from other consumers in several ways which impose further limitations to the value of gut content metabarcoding. The most important difference is the feeding mode and feeding rate, especially for deep-sea species, which typically consume one prey at a time and do not get a chance to capture another until far after the former has been digested [@mackie1988siphonophore]. Therefore, most siphonophores are found with empty guts or digesting one or few prey items at a time. Thus the sample size required for frequency-based analyses is much higher than for other consumers which feed more frequently. Our prey frequency results are consistent with this idea. Moreover, with the exception of a couple species such as *Rhizophysa* and *Rosacea* which are diurnal feeders [@purcell1981dietary], most species also feed during the night. In the open ocean, diel vertical migration drastically changes the prey field composition for siphonophores at night. Given the fieldwork limitations in this study, we were only able to collect siphonophore gut contents during the day, thus likely biasing their diet towards their diurnal prey captures. 

Overall, this investigation was successful in demonstrating the suitability and effectiveness of DNA metabarcoding to identify the prey consumed by siphonophores from gastrozooid contents, providing novel insights into the ecology and natural history of several siphonophore species, assessing prey selectivity in comparison with their prey-field, assessing the biases in visual prey detection methods, and validating the power of tentilla morphology to predict siphonophore diets. We find that siphonophores are specialized and selective predators which have diversified their feeding habits to consume fish, crustaceans, gelatinous predators, gelatinous filter-feeders, meroplanktonic larvae, and other pelagic invertebrates.

## Acknowledgements {-}

We would like to thank Gisella Caccone, Carol Mariani, and T.J. Johnson for the Yale DNA Analysis Facility for their invaluable training and their assistance on this study, as well as the staff of the Yale Center for Genomic Analyses for helping us design the sequencing strategy for this study, and the Yale Center for Research Computing for providing assistance with high-performance computing. We also wish to thank Bianca R. Brown for her assistance designing the read processing pipeline and Johan Bengtsson-Palme for his help troubleshooting our usage of METAXA2. We are grateful to the crew of the R/V Western Flyer, the R/V Kilo Moana, the Bermuda Institute of Ocean Sciences, and Jeff Godfrey for making the collection of these samples possible. This research was funded by the Yale Institute of Biospheric Studies through a Doctoral Dissertation Improvement Award to A.D.-S., as well as by NSF-OCE 1829835 (to C.W.D.), OCE-1829805 (to S.H.D.H.), and OCE-1829812 (to C.A.C.).

## References {-}



